### ISSUE TITLE
Frame time?

### ISSUE THREAD

**Issue by antithing** [belosthomas/libCML#1]
Hi, and thank you for making this code available! Quick question, does this code use the cpu only, or the gpu as well? What is the average frame time for a stereo slam frame, for example in the kitti dataset?

Thanks!

**Comment by lizabelos** [comment]
This code uses the CPU Only. It uses AVX, SSE, and Neon for image processing. 
We did not implement stereo yet, so this code use only the left frames of the pairs of KITTI images. But it would be fast and easy to add. For KITTI, I obtained these processing times on an i7 when launching 10 SLAM at the same times (it was during the parameters tuning):
Indirect Pose Estimation 0.005s ± 0.001
Direct Pose Estimation 0.002s ± 0.002
Indirect Bundle Adjustment 0.16s ± 0.02
Direct Bundle Adjustment 0.14s ± 0.02

(Sorry for the response time)
